language: minimal

# Install Hugo
install:
  - url=https://github.com/gohugoio/hugo/releases/download/v0.32.4/hugo_0.32.4_Linux-64bit.deb
  - echo $url
  - curl -OLkSs $url
  - sudo dpkg -i hugo*.deb

script:
  - git clone https://github.com/sean-ww/hugo-nuo themes/hugo-nuo
  - hugo --cleanDestinationDir --ignoreCache --disableKinds=RSS
  - echo 'seanwallis.com' > public/CNAME

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $PA_TOKEN
  local_dir: public
  keep-history: true
  on:
branch: master
