language: minimal

# Install Hugo
install:
  - url=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p;q}}')
  - echo $url
  - curl -OLkSs $url
  - sudo dpkg -i hugo*.deb

script:
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $PA_TOKEN
  local_dir: public
  keep-history: true
  on:
branch: master
