language: minimal

# Install Hugo
install:
  - url=https://github.com/gohugoio/hugo/releases/download/v0.32.4/hugo_0.32.4_Linux-64bit.deb
  - echo $url
  - curl -OLkSs $url
  - sudo dpkg -i hugo*.deb

script:
  - mkdir themes
  - wget https://github.com/sean-ww/hugo-nuo/archive/master.zip - themes/temp.zip; unzip themes/temp.zip; rm themes/temp.zip;
  - mv themes/hugo-nuo-master themes/hugo-nuo
  - hugo --cleanDestinationDir --debug --ignoreCache --verbose
  - echo 'seanwallis.com' > public/CNAME
  - cd public
  - ls
  - cat index.html

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $PA_TOKEN
  local_dir: public
  keep-history: true
  on:
branch: master
